### PR TITLE
getNumSubscribers working method to foxy

### PR DESCRIPTION
**Pull request by simulacrus**
1. Fix Non-working CameraPublisher::getNumSubscribers method
2. fix typos

### CODE REVIEW

**Comment by gbiggs** [comment]
Can you please add a description to your PR? You also need to make sure it only includes changes relevant to your PR.

**Comment by simulacrus** [comment]
> Can you please add a description to your PR? You also need to make sure it only includes changes relevant to your PR.

DONE

**Comment by gbiggs** [comment]
Gist: https://gist.githubusercontent.com/gbiggs/91081f5ae26d1ac74b073dfa8e04b4a6/raw/70cc7a74388daa9be066e8686550f5772027489c/gistfile1.txt
BUILD args: --packages-up-to image_common
TEST args: --packages-select image_common
ROS Distro: foxy
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/9437

- Linux [Build Status](https://ci.ros2.org/job/ci_linux/15875/)
- Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/10552/)
- macOS [Build Status](https://ci.ros2.org/job/ci_osx/13541/)
- Windows [Build Status](https://ci.ros2.org/job/ci_windows/16178/)

**Comment by gbiggs** [comment]
It's been a while, so re-running CI.

- Linux [Build Status](https://ci.ros2.org/job/ci_linux/16427/)
- Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/11032/)
- Windows [Build Status](https://ci.ros2.org/job/ci_windows/16795/)

**Comment by gbiggs** [comment]
The Windows instability does not appear related to this PR. Merging!

**Pull request merged**
