### PR TITLE
Add `camera_info_manager_py`

### PR DESCRIPTION
**Pull request by ahcorde**
Adds the `camera_info_manager_py` package for Humble.

See:
- https://github.com/ros-perception/image_common/issues/331#issuecomment-2493971915
- https://github.com/ros/rosdistro/pull/43325

### CODE REVIEW

**Comment by ahcorde** [comment]
Pulls: ros-perception/image_common#335
Gist: https://gist.githubusercontent.com/ahcorde/22eaec62b7954b7c0a5f1ca1110053d9/raw/72b685c91e95d9a60b93b757d999b02881b0d53a/ros2.repos
BUILD args:   --packages-above-and-dependencies camera_info_manager_py --packages-above-and-dependencies camera_info_manager_py
TEST args:  --packages-above camera_info_manager_py --packages-above camera_info_manager_py
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14862
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22174/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16426/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1695/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22918/)

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22175/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16427/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1696/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22919/)

**Comment by ahcorde** [comment]
@civerachb-cpr do you mind to take a look?

**Comment by civerachb-cpr** [comment]
@ahcorde what do you need me to look at? According to https://github.com/ros-perception/image_common/pull/335#issuecomment-2497855334 everything is passing.

The linting changes you made in `a43556e` all seem fine to me.

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy humble

**Pull request merged**
