### PR TITLE
Apply remappings to base topic before creating transport-specific topics

### PR DESCRIPTION
**Pull request by bjsowa**
Related issues:
#237
#171
~#80~ (nvm, this is for ros1)
ros-perception/image_pipeline#839

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
There are conflicts

**Comment by bjsowa** [comment]
> There are conflicts

fixed

**Comment by ahcorde** [comment]
Pulls: ros-perception/image_common#326
Gist: https://gist.githubusercontent.com/ahcorde/00fc5830f0d254b139c3d425891a1b42/raw/73e89122387ef0668397e41386a09ad1e2bdfba8/ros2.repos
BUILD args:  --packages-above-and-dependencies  image_transport --packages-above-and-dependencies image_transport
TEST args:  --packages-above image_transport --packages-above image_transport
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14649
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21933/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16200/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1447/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22659/)

**Comment by bjsowa** [comment]
@ahcorde Can this and/or #325 be backported to Jazzy?

**Comment by ahcorde** [comment]
I can backport #325, but this one looks like a behavioral change.

**Comment by Tacha-S** [comment]
Does the fact that this fix won’t be backported to Jazzy mean that the issue where the compressed topic isn’t remapped to match the base topic wasn’t considered a bug?

**Comment by berndpfrommer** [comment]
This PR also fixes [some crashes in the plugins](https://github.com/ros-perception/image_transport_plugins/issues/155), where it is implicitly assumed that the name space is prefixing the image topic.

**Pull request merged**
