### PR TITLE
Add alias library targets for all libraries

### PR DESCRIPTION
**Pull request by RFRIEDM-Trimble**
In support of #245, this is one one of the steps.

### CODE REVIEW

**Review by gbiggs — APPROVED** [review]

**Comment by gbiggs** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17632/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12180/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18207/)

**Comment by RFRIEDM-Trimble** [comment]
Once this is merged, I'd like to request a backport to humble and galactic, and same for the follow up PR's (coming soon). Is that OK?

**Comment by gbiggs** [comment]
Yep that's possible.

**Comment by gbiggs** [comment]
Thanks for the contribution!

**Comment by RFRIEDM-Trimble** [comment]
> Yep that's possible.

Thanks! Is it something I can trigger, or only maintainers?

**Comment by gbiggs** [comment]
I'm working on them here.
https://github.com/ros-perception/image_common/pull/260
https://github.com/ros-perception/image_common/pull/261

**Pull request merged**
