### PR TITLE
[WIP] camera_info_manager port

### PR DESCRIPTION
**Pull request by mjcarroll**

### CODE REVIEW

**Comment by chapulina** [comment]
I commented out some stuff as on #95 and this is working for my needs on `gazebo_ros_pkgs` for now.

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5767/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2351/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4767/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5668/)

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5771/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2352/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4768/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5669/)

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5782/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2358/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4784/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5678/)

**Review by chapulina — APPROVED** [review]
Works for https://github.com/ros-simulation/gazebo_ros_pkgs/pull/827, feel free to merge with green CI.

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5793/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2367/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4793/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5696/)

**Pull request merged**
