### PR TITLE
Fix Travis tests

### PR DESCRIPTION
**Pull request by efernandez**
@vrabaud

### CODE REVIEW

**Comment by efernandez** [comment]
This fixes the tests running with OPENCV=3, but the ones with OPENCV=2 still fail, but for another reason:

``` bash
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
The job has been terminated
```

You need to make the compilation **quiet**. I can try that on this PR if you're OK with that. In fact, I don't think you have another option, AFAIK. Thoughts, @vrabaud @jack-oquin @tfoote ?

**Comment by efernandez** [comment]
I've just passed `-qq` to `apt-get install`, which should help substantially. Let's see if now everything passes.

**Comment by efernandez** [comment]
Passing `-q` to `rosdep install` too, which was actually the one spamming more into the test log.

**Comment by efernandez** [comment]
All green now. Could any of the maintainers please review and merge this? @vrabaud @jack-oquin @jbohren @wjwwood @tfoote

**Comment by efernandez** [comment]
ping

BTW If I'm understand well, you're using `hydro-devel` branch to release for `indigo`, `jade` and `kinetic` too, right?

**Comment by vrabaud** [comment]
Thx ! Haven't had time lately. I'll use that all over. Thx a bunch !!!

**Comment by vrabaud** [comment]
and yes, hydro is used all over: no API change since then.

**Comment by efernandez** [comment]
@vrabaud With the commits after this PR, the travis job still generates more than 4MB output: https://travis-ci.org/ros-perception/image_common/jobs/162462394

~~Maybe there's a config where you can increase that.~~
The main culprit is `rosdep install`, that even with `-q` is still spamming non-error messages. How do you feel about doing `rosdep install ... >/dev/null` ? The errors will still go to `2>`, so it should be a reasonable workaround in principle.

It seems this is NOT the only project bitten by this limitation ;)
https://github.com/travis-ci/travis-ci/issues/3865

**Comment by vrabaud** [comment]
catkin build was the culprit because of the update not handled properly (wrong carriage handling I guess). Now fixed.

**Pull request merged**
