### PR TITLE
fix compiler issue at OS X

### PR DESCRIPTION
**Pull request by fradelg**
add catkin_LIBRARIES to avoid a linker error about x86_64 in camera_calibration_parsers package

### CODE REVIEW

**Comment by vrabaud** [comment]
well, actually, just replace the whole thing by:

```
target_link_libraries(${PROJECT_NAME} ${catkin_LIBRARIES})
```

no ? That will work on Linux too. The libraries were itemized but there is no point.

**Comment by fradelg** [comment]
Ummm, you`re right! This change should be valid in both Linux and OS X.

Do I have to create other pull request with the suggested change?

**Comment by vrabaud** [comment]
please confirm that it works for you and I'll release it

**Comment by fradelg** [comment]
Yes, it works in OS X now. Thanks for release it!

**Pull request closed without merging**
