### PR TITLE
Backport #259 to humble

### PR DESCRIPTION
**Pull request by gbiggs**
Signed-off-by: Geoffrey Biggs <gbiggs@killbots.net>

### CODE REVIEW

**Comment by gbiggs** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17636/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12184/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18211/)

**Comment by gbiggs** [comment]
Trying CI again:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17641/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12196/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18216/)

**Comment by RFRIEDM-Trimble** [comment]
Very odd, the last Linux build is failing because package not found. Your diff has nothing to do with the package name or finding of it.  I don't have any suggestions at this point. 
`Package 'polled_camera' specified with --packages-up-to was not found`

**Comment by gbiggs** [comment]
Yeah, it turns out that `polled_camera` isn't built for ROS 2. There's a `COLCON_IGNORE` file in its directory.

**Comment by gbiggs** [comment]
Here's some CI skipping `polled_camera`.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17648/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12203/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18223/)

**Comment by gbiggs** [comment]
The instability does not appear to be related to this PR.

**Pull request merged**
