### PR TITLE
Add missing include set

### PR DESCRIPTION
**Pull request by galou**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Duplicate of https://github.com/ros-perception/image_common/pull/140 ?

**Comment by galou** [comment]
Yes, same symptoms, slightly different solution (include either in header or source). Choose the one you prefer (I prefer in the source).

**Comment by mjcarroll** [comment]
Since the set isn't used in the header, I think it makes the most sense to keep it in the source.

Are you seeing this problem after #140 has landed?

**Comment by galou** [comment]
I must have pulled a few commit before it (I had e4538a8). Sorry for the noise. Things go quickly here!

**Pull request closed without merging**
