### PR TITLE
Add support for missing CameraInfo.msg fields

### PR DESCRIPTION
**Pull request by ghost**
Missing (and added) fields are:
binning_x
binning_y
roi.x_offset
roi.y_offset
roi.height
roi.width
roi.do_rectify

We (and I think also other developers) need to be able to set a certain ROI in our camera driver. So we added support for these fields in the YAML parser. It is fully backwards compatible, with old config files.

### CODE REVIEW

**Comment by UniBwTAS** [comment]
@mjcarroll Do you have any thoughts on this pull request?

**Comment by UniBwTAS** [comment]
@ahcorde Can you review this pull request?

**Comment by gbiggs** [comment]
The additions look OK to me, but I'm going to get a second opinion just in case.

Have you got a test that has the existing fields but _not_ your new ones, to verify that existing configuration files will work without errors?

**Comment by clalancette** [comment]
I didn't do a detailed review, but it does look like this is backwards compatible.  So I'd say this is generally OK.

**Comment by clalancette** [comment]
I didn't do a detailed review, but it does look like this is backwards compatible.  So I'd say this is generally OK.

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
