### PR TITLE
Add camera_calibration_parsers dependency to camera_info_manager

### PR DESCRIPTION
**Pull request by mxsrc**
Proposed fix for #62 
I pulled up the components lookup to ensure they can be found, because catkin_package expects its CATKIN_DEPENDS to be find_package-able.

### CODE REVIEW

**Comment by jack-oquin** [comment]
Your fix looks good. 

I don't know why the Travis CI tests are failing, maybe due to something else.

**Comment by vrabaud** [comment]
I fixed the failing test. I am not sure why you need CATKIN_DEPENDS here: calibration parsers is not part of the public headers and the camera_info lib should be transparently linked to calibration parsers.

**Comment by mxsrc** [comment]
Without the change the generated camera_info_managerConfig.cmake sets the required libraries only to its own library which made linking a depending package fail for me.

**Comment by vrabaud** [comment]
But that's the thing, if you depend on camera_info_manager, you are not going to link again to camera_calibration_parsers, you should not, this is something internal to camera_info_manager, there is no public interface dealing with camera_calibration_parsers.
BTW, the find_package was totally wrong (having two find_package(catkin) overwrote the catkin_LIBRARIES values). Not sure why it worked on Travis, but the farm totally barfed (e.g. http://build.ros.org/job/Jdev__image_common__ubuntu_trusty_amd64/17/console). Fixed now.

**Comment by mxsrc** [comment]
Oh, I overlooked the second find_pacakge call for catkin. I am not sure why my build failed w/o this.
Looking at other packages (e.g. roscpp) they seem to add their dependencies' libraries to their own. I don't know why, it might be that with non-install builds every package has their own link-directory which would need to be supplied, but that shouldn't be the reason.

**Pull request merged**
