### PR TITLE
Revert "Image transport tutorial (#197)"

### PR DESCRIPTION
**Pull request by clalancette**
This reverts commit 8cef3db2234a0bc4b8ede533828ee1adc1ff8feb.

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14958/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9698/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12635/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15121/)

**Review by mjcarroll — APPROVED** [review]
That's on me.  I thought I saw CI, merged too quickly.

**Comment by Ace314159** [comment]
Btw, I made #200 that fixes the build, which we've tested on Windows and Mac OS. Instead of reverting, would it be better to merge my fix instead?

**Comment by clalancette** [comment]
> Btw, I made #200 that fixes the build, which we've tested on Windows and Mac OS. Instead of reverting, would it be better to merge my fix instead?

Unfortunately, that is not enough.  The basic problem is that `cv_bridge` isn't available in our CI right now, and so this fails to compile on all platforms.  We'll have to consider that as well as your fix once we try to get the PR back in.

**Comment by jacobperron** [comment]
After an offline discussion we'll move the tutorials package to its own repo: https://github.com/ros-perception/image_transport_tutorials

**Pull request merged**
