### PR TITLE
Fix CMakeLists of image_transport/tutorial + polled_camera

### PR DESCRIPTION
**Pull request by mintar**
There were many errors in those CMakeLists, including duplicate
catkin_package stanzas etc.

I didn't have time to clean up the other packages
(camera_calibration_parsers, camera_info_manager, image_transport). I
recommend running catkin_lint on those as well.

This PR fixes compilation of image_transport/tutorial on Kinetic.

### CODE REVIEW

**Comment by jack-oquin** [comment]
Thanks for the fixes.

+1 looks good to me; with a minor comment that it's better to alphabetize lists of dependencies and components, making it easier to see what's missing.

**Comment by mintar** [comment]
> it's better to alphabetize lists of dependencies and components

I tried but failed. Alphabetization is hard! ;-)

Fixed now.

**Comment by jack-oquin** [comment]
I have trouble with it, too. Just seems so arbitrary. Fortunately, there's the emacs ``sort-lines`` command, if you put them on separate lines. :smile:

**Comment by jack-oquin** [comment]
@vrabaud: I'll merge this, if you like.

**Comment by vrabaud** [comment]
Thx !

**Pull request merged**
