### PR TITLE
Fix downstream regressions due to subscribe overloads

### PR DESCRIPTION
**Pull request by adityapande-1995**
Fixes https://github.com/ros-perception/image_common/issues/279 for humble

### CODE REVIEW

**Comment by saikishor** [comment]
Hello!

When can we expect this to be merged?

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
@adityapande-1995 can you run ci?

**Comment by saikishor** [comment]
@ahcorde 
Thank you for such an imminent response. It's just that the recent changes broke some downstream packages. Thanks for understanding :)

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19341/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13868/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20062/)

**Comment by saikishor** [comment]
Hello @ahcorde!

Once the upstream build pass, could you tag and release it as well?

Thank you,

Best Regards,
Sai

**Comment by ahcorde** [comment]
@saikishor done here https://github.com/ros/rosdistro/pull/38240#event-10088006573

**Comment by saikishor** [comment]
Thanks a lot @ahcorde

**Pull request merged**
