### PR TITLE
Noetic release image_common

### PR DESCRIPTION
**Pull request by ahcorde**
Porting Python to Python3 for the noetic release

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by ahcorde** [comment]
@ros-pull-request-builder retest this please

**Comment by sloretz** [comment]
@ros-pull-request-builder retest this please

**Comment by sloretz** [comment]
Clsoing and reopening to see if that [triggers this job](http://build.ros.org/view/Npr/job/Npr__image_common__ubuntu_focal_amd64/)

**Comment by sloretz** [comment]
Manually triggered a PR job: http://build.ros.org/view/Npr/job/Npr__image_common__ubuntu_focal_amd64/1/console

[Build Status](http://build.ros.org/view/Npr/job/Npr__image_common__ubuntu_focal_amd64/1/)

**Comment by sloretz** [comment]
Manually triggered a PR job http://build.ros.org/view/Npr/job/Npr__image_common__ubuntu_focal_amd64/1/console

**Comment by sloretz** [comment]
[Build Status](http://build.ros.org/view/Npr/job/Npr__image_common__ubuntu_focal_amd64/3/)

**Comment by ahcorde** [comment]
It's green @sloretz

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
