### PR TITLE
Expose callback groups - backport to iron

### PR DESCRIPTION
**Pull request by adityapande-1995**
This PR backports https://github.com/ros-perception/image_common/pull/274 to ros iron. Yet to check for ABI compatibility using a https://lvc.github.io/abi-compliance-checker/

### CODE REVIEW

**Comment by ahcorde** [comment]
@adityapande-1995 is this ready for a review?

**Comment by adityapande-1995** [comment]
Open for review, I have to run the ABI checker to verify compatibility.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19234/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13789/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19975/)

**Review by ahcorde — APPROVED** [review]

**Comment by adityapande-1995** [comment]
image

**Pull request merged**
